### ISSUE TITLE
[7002] Download file

### ISSUE THREAD

**Issue by Eduardo1977** [italia/anpr-client-example#10]
Buongiorno, 
vorrei utilizzare il client per richiamare il servizio 7002, ma ho fatto qualche prova senza successo.
&lt;ns2:Richiesta7002 xmlns:ns2="http://sogei.it/ANPR/7001scaricoTabelle"&gt;
&lt;testataRichiesta&gt;
&lt;idOperazioneComune&gt;ServLoc1005842&lt;/idOperazioneComune&gt;
&lt;codMittente&gt;006017&lt;/codMittente&gt;
&lt;codDestinatario&gt;ANPR02&lt;/codDestinatario&gt;
&lt;operazioneRichiesta&gt;7002&lt;/operazioneRichiesta&gt;
&lt;dataOraRichiesta&gt;2019-06-12T11:03:05.746+02:00&lt;/dataOraRichiesta&gt;
&lt;tipoOperazione&gt;C&lt;/tipoOperazione&gt;
&lt;tipoInvio&gt;PROD&lt;/tipoInvio&gt;
&lt;dataDecorrenza&gt;2019-06-12&lt;/dataDecorrenza&gt;
&lt;/testataRichiesta&gt;
&lt;datiRichiesta&gt;
&lt;idOperazioneANPR&gt;89227510&lt;/idOperazioneANPR&gt;
&lt;/datiRichiesta&gt;
&lt;/ns2:Richiesta7002&gt;

Riguardando il codice cdel client mi viene qualche dubbio che possa funzionare, o su come fare per richiamare il servizio in maniera corretta (per esempio, da linea di comando va usato WS7001 o WS7002 ?). Potete confermarmi se è stato fatto qualche test con esito positivo? Grazie   

Comune di Bistagno (AL), ambiente PROD

**Comment by gife67** [comment]
Buongiorno, 
dovrebbe utilizzare il parametro WS7002, ma non è detto che la versione del client lo supporti essendo una nuova operation. Il client è fornito a titolo di esempio e non viene aggiornato ad ogni cambiamento dei WSDL/XSD. Aggiungere una nuova operation è abbastanza semplice esaminando i sorgenti. Prossimamente cercheremo di pubblicare la versione aggiornata del client che contenga gli ultimi  WSDL/XSD o magari visto che è stata pubblicata su GitHub, ci potrebbe essere qualche volontario che esegua la modifica.

**Comment by Eduardo1977** [comment]
Grazie per la risposta, riproverò a fare qualche altro tentativo
