### ISSUE TITLE
Avvio da cmd

### ISSUE THREAD

**Issue by kodiex** [italia/anpr-client-example#13]
Ciao, innanzitutto grazie per il tuo lavoro che getta un po' di luce su questi ws.

Io sono nuovo all'ambiente Java, ho guardato un po' l'ambiente e sopratutto maven. Ho tentato la compilazione includendo le librerie con il plug-in shade ma ho più o meno errori di runtime, ultimo un errore di spring:

Configuration problem: Unable to locate Spring NamespaceHandler for XML schema namespace [http://cxf.apache.org/jaxws]
Offending resource: class path resource [cxf.xml]

Credo allora di stare sbagliando per fare una cosa tanto banale quanto apparentemente impossibile: qual'è il metodo raccomandato per invocare il client da linea di comando?

Grazie.

**Comment by gife67** [comment]
Ciao,
a dire il vero sono il dipendente di Sogei che ha realizzato questo client, a titolo di esempio, per poter agevolare la realizzazione della cornice di sicurezza per l'accesso ai WS di ANPR. Questo client è pubblicato su GitHub da un paio di anni, anche se era stato fornito alle varie software house che gestiscono i Comuni già dal 2015. Concedimi di difendere la società per cui lavoro, che tanto viene bistrattata, ma ti assicuro che dietro le quinte c'è un gruppo di persone che ci mette l'anima ogni giorno per gestire l'intero sistema ANPR... smetto di annoiarti con le chiacchiere :-). La segnalazione che evidenzi è solo un warning e non tenerne conto. La classe che avvia il client si chiama it.interno.anpr.security.main.RunSenderMessage, che è l'unica che ha il metodo **main**, utilizzato per avviare applicazioni java standalone. Questa accetta 3 parametri il primo che indica l'ambiente che da quanto intuisco per te dovrebbe essere FREE, il secondo indica l'operations dei WS che vuoi richiamare (es. TESTCONN o WS3002) ed il terzo indica il path di un file che contiene il payload di una richiesta verso l'operation indicata (es. request/TestConn/testConn_FREE.req). Quando esegui il comando maven per la build, ti consiglio in prima battuta di eseguirlo con l'opzione -DskipTests per skippare il Test interno che presuppone avere l'ambiente totalmente configurato con tutto il necessario (file di properties impostato correttamente; file keystore presente nell'apposito path etc),  ti viene generato sotto la directory target il tool-testconn-1.3.0.jar, che rappresenta l'intera applicazione. Per poter far funzionare correttamente l'applicazione devi cambiare il file **FREE_Keystore.properties** che trovi sotto src/main/resources/config, con i parametri che ne conseguono alla tua richiesta di abilitazione che devi effettuare al Team Digitale, per poter aver accesso all'ambiente di FreeTest di ANPR, ambiente dedicato agli sviluppatori non ancora accreditati a lavorare su ANPR. Otterrai un utenza ed un keystore nel formato 888xxx-CO-0000.p12 che dovrai inserire nella directory keystore/FREE e che punterai con uno dei parametri del file di properties insieme alla sua password. Se vuoi crearti una struttura ad hoc per l'esecuzione standalone devi crearti una directory e sotto creare una struttura come questa 
![dir](https://user-images.githubusercontent.com/26840080/70153442-3acfb480-16af-11ea-8e88-9cb8d7c56eb5.JPG)
Le directory le trovi nel repository e ci devi mettere i file che ti ho indicato prima. Va creata la lib con tutti i jar indicati nel file MANIFEST all'interno del jar. Questi jar li puoi trovare nel tuo repo maven che si trova nella directory .m2 della tua directory utente di SO. Un esempio di riga di comando per lanciare l'applicazione, una volta che hai l'ambiente correttamente impostato è la seguente:
java -cp tool-testconn-1.3.0.jar;. it.interno.anpr.security.main.RunSenderMessage FREE TESTCONN request/TestConn/testConn_FREE.req 
Diciamo che queste sono le indicazioni di massima, in caso di problemi prova a contattare il Team Digitale che ti daranno ulteriore supporto. Un saluto

**Comment by kodiex** [comment]
si scusami mi sono accorto e ho corretto la mia prima frase, l'equivoco nasce dal fatto che questo preziosissimo client, a mio avviso la risorsa più importante per testare i servizi non è indicata nella pagina ufficiale della doc tecnica di ANPR...

Per il resto grazie, si avevo già configurato e compilato il tutto, il test veniva infatti eseguito correttamente, mi mancava di dover "tirare indietro" il jar da target e aggiungere la cartella lib prelevando i jar dipendenti dal repo di maven. Grazie.
