### ISSUE TITLE
Secure Connection Failed (https://dpfree.anpr.interno.it/combas)

### ISSUE THREAD

**Issue by ghost** [italia/anpr-client-example#2]
I added the exception for the self-signed HTTPS certificate, but looks like it's using unsupported params:

`An error occurred during a connection to dpfree.anpr.interno.it. SSL peer was unable to negotiate an acceptable set of security parameters. Error code: SSL_ERROR_HANDSHAKE_FAILURE_ALERT`

see shots

![screenshot from 2018-05-24 12-48-48](https://user-images.githubusercontent.com/25619972/40480641-68cee464-5f4f-11e8-82e5-54b1500a6eb3.png)
![screenshot from 2018-05-24 12-48-58](https://user-images.githubusercontent.com/25619972/40480642-6923a8a0-5f4f-11e8-8aa5-9c0304e09975.png)

**Comment by gife67** [comment]
Hi,
to connect to the site you must have installed in the browser the certificate that you can download after registration (888xxx-CO-0000.p12). It is a mutual authentication in TLS 1.2.

**Comment by Vytek** [comment]
I have the p12 in my browser: 
![schermata 2018-05-24 alle 11 54 16](https://user-images.githubusercontent.com/2614303/40485006-995521c6-5f5d-11e8-9409-07ee7fa7c955.png)
Also create "exception", the system can't insert login and password:
![schermata 2018-05-24 alle 11 53 54](https://user-images.githubusercontent.com/2614303/40485051-c3aa2dc2-5f5d-11e8-9086-4082e7d01815.png)

**Comment by Vytek** [comment]
Other have the same problems:
https://forum.italia.it/t/un-ambiente-di-test-aperto-a-tutti-per-anpr/3407/5?u=vytek

**Comment by gife67** [comment]
you can try now, with 888013-CO-0000?

**Comment by Vytek** [comment]
OK! I login:
![schermata 2018-05-24 alle 15 14 30](https://user-images.githubusercontent.com/2614303/40487702-44940d2a-5f65-11e8-941c-8e88ef65e90f.png)

**Comment by gife67** [comment]
OK,
we are proceeding to enable all other certificates

**Comment by ghost** [comment]
with cert installed and credentials enabled, I could access the web app.

![screenshot from 2018-05-24 16-10-49](https://user-images.githubusercontent.com/25619972/40490257-6f584318-5f6b-11e8-9317-b79b8c98dab4.png)
