### ISSUE TITLE
MTOM/XOP

### ISSUE THREAD

**Issue by rinonasti** [italia/anpr-client-example#22]
Buongiorno,
Ho configurato tutti i nuovi WS fino ad oggi (compresi P000) e funzionano correttamente, E' STATO SEMPLICISSIMO per me che non sono dell'ambiente JAVA.
Chiedo se qualcuno ha risolto il problema MTOM/XOP (nelle risposte sono 
<xop:Include xmlns:xop="http://www.w3.org/2004/08/xop/include" href=....... e non codifica base64. 
Grazie infinite

**Comment by gife67** [comment]
Buongiorno,
per queste problematiche dovreste aprire delle issue su italia/anpr, controllando prima le issue presenti.
Grazie

**Comment by rinonasti** [comment]
Buongiorno
issue aperta : #3286

Grazie
