### ISSUE TITLE
Rejected by policy. (from client)

### ISSUE THREAD

**Issue by ghost** [italia/anpr-client-example#3]
After adding the certificate file and configuring the "FREE_Keystore.properties" file, I got a XML response like this:

<?xml version="1.0" encoding="UTF-8"?><env:Envelope xmlns:env="http://schemas.xmlsoap.org/soap/envelope/">
    <env:Body>
        <env:Fault>
            <faultcode>env:Client</faultcode>
            <faultstring>Rejected by policy. (from client)</faultstring>
        </env:Fault>
    </env:Body>
</env:Envelope>

Logs attached.

PS: that "FREE_Keystore.properties" is not so clear, let alone duplicated entries:

```
# Properties WSS4J - Keystore del Comune
org.apache.ws.security.crypto.merlin.keystore.file=keystore/FREE/<Nome file keystore>.p12
org.apache.ws.security.crypto.merlin.keystore.password=<Password>
org.apache.ws.security.crypto.merlin.keystore.type=pkcs12
org.apache.ws.security.crypto.merlin.keystore.alias=<ID Postazione>

# Properties internal
ID_OPERATORE=<Username web (USERSFREETEST)>
ID_SEDE=<Codice Comune>
ID_POSTAZIONE=<ID Postazione>
ID_APPLICAZIONE=12345
ID_TRANSAZIONE=99999
PATH_KEYSTORE_POSTAZIONE=keystore/FREE/<Nome file keystore>.p12
PASS_KEYSTORE_POSTAZIONE=<Password>
ALIAS_KEYSTORE_POSTAZIONE=<ID Postazione>
...
```

Maybe this brings in confusion...

cheers
corrado
[failure.txt](https://github.com/italia/anpr-client-example/files/2035511/failure.txt)

**Comment by gife67** [comment]
please, can you retry?

**Comment by ghost** [comment]
just done:

--------------------------------------
2018-05-24 16:06:39 INFO  AnprPortType3000:273 - Inbound Message
----------------------------
ID: 2
Response-Code: 500
Encoding: ISO-8859-1
Content-Type: text/xml
Headers: {connection=[close], content-type=[text/xml],
X-Backside-Transport=[FAIL FAIL]}
Payload: <?xml version="1.0" encoding="UTF-8"?>
<env:Envelope xmlns:env="http://schemas.xmlsoap.org/soap/envelope/"><env:Body><env:Fault><faultcode>env:Client</faultcode><faultstring>Rejected
by policy. (from client)</faultstring></env:Fault></env:Body></env:Envelope>
--------------------------------------
Esecuzione InInterceptor...
Messaggio di Risposta:
<?xml version="1.0" encoding="UTF-8"?><env:Envelope xmlns:env="
http://schemas.xmlsoap.org/soap/envelope/">
    <env:Body>
        <env:Fault>
            <faultcode>env:Client</faultcode>
            <faultstring>Rejected by policy. (from client)</faultstring>
        </env:Fault>
    </env:Body>
</env:Envelope>


2018-05-24 15:54 GMT+02:00 Giuseppe F. <notifications@github.com>:

**Comment by gife67** [comment]
ho fatto la verifica sulla tua richiesta ed il problema è dovuto al fatto che la SAML Assertion risulta expired. Questo è dovuto ad un disallineamento dell'orario del tuo PC con l'ora ufficiale. Basta un disallineamento di 5 minuti ad invalidare la SAML Assertion. Puoi verificare il tutto dal payload del messaggio in uscita. Se imposti l'ora corretta sul tuo PC/Server dovresti risolvere.

**Comment by ghost** [comment]
in effetti l'orario era disallineato (time settato su auto, ma ntp non installato)

ho appena riprovato, dopo aver avviato ntp, ma ottengo lo stesso errore:

```
--------------------------------------
2018-05-24 16:28:13 INFO  AnprPortTypeTestConn:273 - Inbound Message
----------------------------
ID: 2
Response-Code: 500
Encoding: ISO-8859-1
Content-Type: text/xml
Headers: {connection=[close], content-type=[text/xml], X-Backside-Transport=[FAIL FAIL]}
Payload: <?xml version="1.0" encoding="UTF-8"?>
<env:Envelope xmlns:env="http://schemas.xmlsoap.org/soap/envelope/"><env:Body><env:Fault><faultcode>env:Client</faultcode><faultstring>Rejected by policy. (from client)</faultstring></env:Fault></env:Body></env:Envelope>
--------------------------------------
Esecuzione InInterceptor...
Messaggio di Risposta: 
<?xml version="1.0" encoding="UTF-8"?><env:Envelope xmlns:env="http://schemas.xmlsoap.org/soap/envelope/">
    <env:Body>
        <env:Fault>
            <faultcode>env:Client</faultcode>
            <faultstring>Rejected by policy. (from client)</faultstring>
        </env:Fault>
    </env:Body>
</env:Envelope>
```
l'errore dovrebbe essere sotto il minuto, adesso

**Comment by gife67** [comment]
scusa potresti riprovare

**Comment by ghost** [comment]
continua a non andare, vedi allegato

[stillFails.txt](https://github.com/italia/anpr-client-example/files/2038104/stillFails.txt)

aggiungo che ho solo impostato le credenziali:

```
servicemix@powerdesk:~/GIT_LOCAL/anpr-client-example$ git graphlog 
* e5dc34e (HEAD -> credenzialiTest) configurazione credenziali completa, errore auth server
* 0138eb6 email e certificato per credenziali di test
* 2187a95 (origin/master, origin/HEAD, master) Update README.md - fix typo
* 3907b39 Add references and links to Slack and Developers Italia
* 07d5d5c Aggiungi documentazione su webapp
* 7626131 Delete message_in.xml
* 1c1b0df Aggiorna file di credenziali specificando il parametro username
* 0de1756 Update README.md
* ac22a49 Update LICENSE
* 86f91df Add AUTHORS file
* e65e87c Initial commit
```

allego diff col master remoto:
[gitDiffMaster.txt](https://github.com/italia/anpr-client-example/files/2038107/gitDiffMaster.txt)

ho impostato male le credenziali?

![screenshot from 2018-05-25 07-51-01](https://user-images.githubusercontent.com/25619972/40528209-6a358fdc-5ff0-11e8-95f2-00937afa490d.png)

**Comment by gife67** [comment]
Ciao,
ho esaminato il tuo tentativo che risulta effettuato alle 07:41:15, come si evince nell'assertion SAML del messaggio che hai inoltrato
<saml2:Conditions NotBefore="2018-05-25T05:41:15.133Z" NotOnOrAfter="2018-05-25T05:46:15.133Z"/>

La trace sul sistema di sicurezza relativamente alla tua richiesta risulta alle 07:40:02,
quindi l'assertion SAML ancora non è valida, come specificato nel campo NotBefore.
C'è qualcosa che non va ancora con l'orario del tuo PC, se lo puoi settare 2 minuti indietro, dovrebbe andare.

**Comment by ghost** [comment]
ok

ho spostato l'orario su manuale e ho tolto 3 minuti, ora da' BUILD SUCCESS.

Il vostro server e' sincronizzato con [NTP](https://it.wikipedia.org/wiki/Network_Time_Protocol) o no?


PS: il primo messaggio passa ok:
```
--------------------------------------
Esecuzione InInterceptor...
Messaggio di Risposta: 
<?xml version="1.0" encoding="UTF-8"?><soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/">
    <soapenv:Body>
        <a:RispostaConnessione xmlns:a="http://sogei.it/ANPR/connessione">
            <testataRisposta>
                <idOperazioneComune>1</idOperazioneComune>
                <codMittente>aaaaaa</codMittente>
                <codDestinatario>giusep</codDestinatario>
                <operazioneRichiesta>OP01</operazioneRichiesta>
                <dataOraRichiesta>2017-03-23T17:22:44.868+01:00</dataOraRichiesta>
                <protocolloComune>111</protocolloComune>
                <dataProtocolloComune>2017-03-23+01:00</dataProtocolloComune>
                <dataDecorrenza>2017-03-23+01:00</dataDecorrenza>
                <idOperazioneANPR>000000000000000000000000000200</idOperazioneANPR>
                <esitoOperazione>0000</esitoOperazione>
            </testataRisposta>
        </a:RispostaConnessione>
    </soapenv:Body>
</soapenv:Envelope>
```

il secondo riporta (nell'XML di RS) un messaggio di errore/anomalia:

```
--------------------------------------
Esecuzione InInterceptor...
Messaggio di Risposta: 
<?xml version="1.0" encoding="UTF-8"?><soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/">
    <soapenv:Body>
        <a:Risposta3002 xmlns:a="http://sogei.it/ANPR/3000consultazione">
            <a:rispostaKO>
                <testataRisposta>
                    <idOperazioneComune>999997</idOperazioneComune>
                    <codMittente>888002</codMittente>
                    <codDestinatario>ANPR00</codDestinatario>
                    <operazioneRichiesta>3002</operazioneRichiesta>
                    <dataOraRichiesta>2017-03-27T19:20:11.543+02:00</dataOraRichiesta>
                    <idOperazioneANPR>0</idOperazioneANPR>
                    <esitoOperazione>XXXX</esitoOperazione>
                </testataRisposta>
                <listaErrori>
                    <errore>
                        <codiceErroreAnomalia>XXXX</codiceErroreAnomalia>
                        <tipoErroreAnomalia>E</tipoErroreAnomalia>
                        <testoErroreAnomalia>Utente non autorizzato : 888002 errato</testoErroreAnomalia>
                    </errore>
                </listaErrori>
            </a:rispostaKO>
        </a:Risposta3002>
    </soapenv:Body>
</soapenv:Envelope>

```

**Comment by gife67** [comment]
si certo è sincronizzato con NTP. 
L'anomalia è corretta, perchè invocando un servizio reale ci sono una serie di controlli, tra cui quello che il messaggio predisposto per il test utilizza come codMittente 888002, se vuoi cambiare il comportamento devi inserire come codMittente il Comune a te assegnato che è il 888046, questo nel file di scenario del test che trovi in request/3002/3002_888002_FREE.req. Ovviamente questo fa parte di tutti gli adattamenti necessari per poter utilizzare correttamente il sistema ANPR.

**Comment by ghost** [comment]
sull'anomalia: in effetti col codice mittente corretto risponde senza anomalia:

```
Messaggio di Risposta: 
<?xml version="1.0" encoding="UTF-8"?><soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/">
    <soapenv:Body>
        <a:RispostaConnessione xmlns:a="http://sogei.it/ANPR/connessione">
            <testataRisposta>
                <idOperazioneComune>1</idOperazioneComune>
                <codMittente>aaaaaa</codMittente>
                <codDestinatario>giusep</codDestinatario>
                <operazioneRichiesta>OP01</operazioneRichiesta>
                <dataOraRichiesta>2017-03-23T17:22:44.868+01:00</dataOraRichiesta>
                <protocolloComune>111</protocolloComune>
                <dataProtocolloComune>2017-03-23+01:00</dataProtocolloComune>
                <dataDecorrenza>2017-03-23+01:00</dataDecorrenza>
                <idOperazioneANPR>000000000000000000000000000200</idOperazioneANPR>
                <esitoOperazione>0000</esitoOperazione>
            </testataRisposta>
        </a:RispostaConnessione>
    </soapenv:Body>
</soapenv:Envelope>
```

**Comment by eliabrugnoni** [comment]
Buongiorno,
anche io ricevo un errore identico, ho sincronizzato la data del server con NTP e non funzionando ancora l'ho modificata portandola indietro di due minuti:
<saml2:Conditions NotBefore="2020-11-13T14:16:15.151Z" NotOnOrAfter="2020-11-13T14:21:15.151Z" />
Come posso verificare la data del sistema di sicurezza per capire se l'assertion SAML risulti valido?

**Comment by gife67** [comment]
Buongiorno,
non è detto che l'errore "Rejected by policy (from client)" sia esclusivamente causato dal Timestamp, occorre esaminare la richiesta che state effettuando per verificare altre potenziali problematiche. Se mi allega la richiesta effettuata che può estrarre dal file message.out ed il log completo dell'esecuzione del client posso provare a controllare eventuali altre problematiche. Cortesemente dovrebbe aprire una nuova Issue collegata a questa per permetterci di assisterla correttamente.
Cordiali Saluti

**Comment by eliabrugnoni** [comment]
Buonasera,
Infatti ho notato validando l'XML di richiesta con l'XSD che l'errore era causato da un elemento errato.
Ora risponde correttamente solo che non riesco a scaricare il certificato...
Il java risponde correttamente ma quando provo a salvare parsando il risultato del java non prende la codifica (inserisce tutti caratteri '?') e quindi non riesco ad effettuare il salvataggio.
Nel file generato (in allegato
[message_in_20201113162358683.txt](https://github.com/italia/anpr-client-example/files/5538414/message_in_20201113162358683.txt)

) invece ho solo il riferimento al "cid" ma da non saprei come poterlo scaricare.
Esiste un'altra soluzione?

Grazie per la risposta

**Comment by gife67** [comment]
Il servizio è configurato con il protocollo MTOM, quindi il PDF del certificato si trova nell'attachment, subito dopo l'XML della risposta. Non deve tentare di estrarlo dal message_in, ma lo deve gestire via software, basterà leggere il contenuto del campo certificatoPdf all'interno di Risposta6001OK.file.

**Comment by eliabrugnoni** [comment]
Ok, 
grazie mille della celere risposta.
Ho verificato e modificato il file java per poter salvare il pdf in una cartella.
