### ISSUE TITLE
Creazione certificati tramite WS6001, Internal Error??

### ISSUE THREAD

**Issue by Vytek** [italia/anpr-client-example#6]
Il certificato è stato correttamente prodotto tramite WebApp. Stiamo cercando di ottenere i dati del certificato tramite Web Service. I test già presenti nel App di test opportunamente cambiati funzionano correttamente. Abbiamo aggiunto un nuovo test, ma viene ritornato un "errore interno":

In ConnessioneFreeTest.java
`@Test
	public void test_6001OnFree() throws Exception {
		ParamHandler param = new ParamHandler();
		param.setEnvironment(EnvironmentHandler.FREE);
		WSTypeHandler wsHandler = new WSTypeHandler();
		wsHandler.setWSFamily(WSTypeHandler.WS6001);
		param.setWsType(wsHandler);
		param.setFileRequest("request/6001/6001_888013_FREE.req");
		DispatchHandler dispatch = new DispatchHandler(param);
		assert(dispatch.execute());
	}`

File: ../ANPR/anpr-client-example/request/6001/
`<ns2:Richiesta6001 xmlns:ns2="http://sogei.it/ANPR/6001certificazione">
       <testataRichiesta>
          <idOperazioneComune>999998</idOperazioneComune>
          <codMittente>888013</codMittente>
          <codDestinatario>ANPR00</codDestinatario>
          <operazioneRichiesta>6001</operazioneRichiesta>
          <dataOraRichiesta>2018-05-28T10:20:11.543+02:00</dataOraRichiesta>
          <tipoOperazione>C</tipoOperazione>
          <tipoInvio>FREE</tipoInvio>
          <dataDecorrenza>2018-05-28T10:20:11.543+02:00</dataDecorrenza>
          <dataDefinizionePratica>2018-05-28T10:20:11.543+02:00</dataDefinizionePratica>
          <nomeApplicativo>APPLIANCE</nomeApplicativo>
          <versioneApplicativo>1</versioneApplicativo>
          <fornitoreApplicativo>GT50SRL</fornitoreApplicativo>
       </testataRichiesta>
       <listaTipiCertificati>
            <tipoCertificato>8</tipoCertificato>
        </listaTipiCertificati>
        <soggettoIntestatario>
            <generalita>
               <cognome>SPERANZA</cognome>
               <nome>ENRICO</nome>
            </generalita>
         </soggettoIntestatario>
         <datiControllo>
            <cognomeUffAnagrafe>PIPPO</cognomeUffAnagrafe>
            <nomeUffAnagrafe>PAPERINO</nomeUffAnagrafe>
            <tipoRichiedente>2</tipoRichiedente>
            <tipoRichiesta>1</tipoRichiesta>
            <paEstera>0</paEstera>
            <emissione>2</emissione>
            <bollo>0</bollo>
        </datiControllo>
</ns2:Richiesta6001>
`

[error.log](https://github.com/italia/anpr-client-example/files/2048343/error.log)
[6001_888013_FREE.req.txt](https://github.com/italia/anpr-client-example/files/2048388/6001_888013_FREE.req.txt)
[ConnessioneFreeTest.java.zip](https://github.com/italia/anpr-client-example/files/2048414/ConnessioneFreeTest.java.zip)

Dove stiamo sbagliando?

**Comment by ruphy** [comment]
Ciao @Vytek, purtroppo non ho idea di come aiutarti: aggiungo @gife67 in CC!

**Comment by gife67** [comment]
Ciao,
il problema è relativo alla validazione della vostra richiesta che presenta i seguenti problemi:
- il campo dataDecorrenza deve essere un Date
- il campo dataDefinizionePratica deve essere un Date
- in datiControllo come ultimo campo deve essere inserito il nodo <diritti> che potete settare a 0

Vi consiglio di eseguire il download degli ultimi WSDL/XSD di tutti i WS dal portale ANPR, vi riporto il link:
https://www.anpr.interno.it/portale/documents/20182/239162/SPECIFICHE_DI_INTERFACCIA_XSD_15052018.rar/a62bee5c-a447-415d-9d74-801cfa809170
Se andate sul portale (www.anpr.interno.it) li trovate sotto "Specifiche per l'accesso ai servizi di ANPR" e poi sul link "Tracciati XSD - WSDL - rar"

Prima di eseguire una qualsiasi richiesta vi consiglio di sottoporla a validazione con gli XSD aggiornati.
A fronte di errori di validazione il sistema ANPR risponde con un "Internal Error (from client)".

**Comment by gife67** [comment]
nella lista dei problemi il terzo punto non mi ha riportato il nome del nodo, perchè delimitato dai caratteri "<>". Il campo si chiama **diritti**

**Comment by Vytek** [comment]
Stiamo ri-verificando tutto, presto faremo una pull request per l'integrazione del codice con magari un ulteriore MarkDown che entri nel dettaglio per spiegare il tutto.

Grazie in ogni caso! ;-)
