### ISSUE TITLE
Problemi creando il pacchetto dist: Configuration problem: Unable to locate Spring NamespaceHandler for XML schema namespace [http://cxf.apache.org/jaxws]

### ISSUE THREAD

**Issue by Vytek** [italia/anpr-client-example#8]
Dopo aver creato un pacchetto con le dipendenze complete tramite il comando:

`mvn clean install -P singlepackage`

alla chiamata:

`java -jar dist-tool-testconn-1.3.0.jar FREE TESTCONN /Users/enricosperanza1/Desktop/ANPR/anpr-client-example/request/TestConn/testConn_FREE.req`

Ottengo:

[error4.log](https://github.com/italia/anpr-client-example/files/2072484/error4.log)

Premetto che: 
1) Il jar relativo è, ho verificato, inserito correttamente nel file pom.xml come indicato in:
[https://stackoverflow.com/questions/37689603/unable-to-locate-spring-namespacehandler-for-xml-schema-namespace-http-cxf-ap/37695423?utm_medium=organic&utm_source=google_rich_qa&utm_campaign=google_rich_qa](https://stackoverflow.com/questions/37689603/unable-to-locate-spring-namespacehandler-for-xml-schema-namespace-http-cxf-ap/37695423?utm_medium=organic&utm_source=google_rich_qa&utm_campaign=google_rich_qa)

Stesso errore per MacOSX, Windows e Linux.

Dove stiamo sbagliando?

**Comment by gife67** [comment]
Come vi ho dettagliato per email,
sconsiglio l'utilizzo del profile -singlepackage perchè un refuso di alcune prove interne.
